import { Product } from "@/types/product";

export const PRODUCTS: Product[] = [
  {
    id: "rt-001",
    name: "Game Boy Color — Atomic Purple",
    slug: "game-boy-color-atomic-purple",
    category: "Retro Gaming",
    shortDescription: "A forgotten 1998 classic rebuilt with an ultra-bright laminated IPS display, custom audio amplifier, and USB-C fast charging.",
    description: "The Atomic Purple Game Boy Color was the defining icon of late-90s portable engineering. This unit was salvaged from a warehouse in Yaba, Lagos with severe battery terminal corrosion, a scratched unlit reflective panel, and dead capacitors. We stripped the unit down to bare silicon, ultrasonically descaled the PCB, upgraded all electrolytic capacitors to tantalum components, retrofitted a laminated FunnyPlaying 2.6\" IPS backlight display with 5 retro pixel-grid filters, and integrated a 1800mAh LiPo cell with discreet USB-C charging.",
    price: 185000,
    originalReleaseYear: 1998,
    edition: "01 / 03",
    status: "available",
    stock: 2,
    era: "90s",
    condition: "Pristine Upgraded",
    featured: true,
    dropId: "drop-001",
    dropName: "DROP 001 — THE REBIRTH COLLECTION",
    highlightTag: "1 OF 3 RELEASE",
    storyQuote: "This machine spent 22 years forgotten in a humid drawer. Today, its phosphor purple heart beats faster and clearer than the day it left Kyoto.",
    beforeImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1000&q=80",
    afterImage: "https://images.unsplash.com/photo-1531525645387-7f14be1bdbbd?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1531525645387-7f14be1bdbbd?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1200&q=85",
    ],
    specifications: [
      { label: "Base Hardware", value: "Nintendo Game Boy Color (CGB-001, 1998)" },
      { label: "Display Architecture", value: "Laminated 2.6\" IPS Panel with OSD menu & 5 retro scanline modes" },
      { label: "Audio Overhaul", value: "CleanAmp Pro v1.2 with Japanese ceramic speaker & zero-hum filtering" },
      { label: "Power System", value: "1,800 mAh LiPo with overcharge protection and USB-C port" },
      { label: "Shell & Buttons", value: "Original UV-stabilized Atomic Purple shell with cast brass tactile D-pad" },
      { label: "Capacitor Type", value: "High-temperature solid tantalum SMD capacitors" },
      { label: "Edition Authenticity", value: "Hand-etched serial plate RT-GBC-001 (Numbered 01 / 03)" },
    ],
    restorationStages: [
      {
        stage: "FOUND",
        title: "01 — Deep Storage Recovery",
        description: "Recovered in a locked storage container. The alkaline AA batteries had ruptured in 2004, eating through the ground traces and crusting the speaker coil.",
        image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "DISASSEMBLED",
        title: "02 — Component Separation",
        description: "Separated into 42 distinct mechanical and electrical sub-assemblies. The original reflective LCD was carefully archived.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "RESTORED",
        title: "03 — Ultrasonic Descaling & Trace Repair",
        description: "PCB submerged in neutralizer solution, micro-jumpered with 0.05mm enameled copper wire to restore severed voltage lines.",
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "UPGRADED",
        title: "04 — IPS Backlight & LiPo Integration",
        description: "Precision CNC milled inner shell clearance to seat the laminated glass IPS panel and custom USB-C charging breakout board.",
        image: "https://images.unsplash.com/photo-1531525645387-7f14be1bdbbd?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "TESTED",
        title: "05 — Thermal & Audio Oscilloscope QC",
        description: "Continuous 12-hour stress testing on Pokemon Crystal under thermal imaging to confirm cool power delivery and noiseless headphone output.",
        image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "REBORN",
        title: "06 — Drop Commissioning",
        description: "Sealed in anti-static ESD packaging with certificates of restoration, bespoke velvet protective pouch, and braided magnetic USB-C cable.",
        image: "https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?auto=format&fit=crop&w=800&q=80",
      },
    ],
  },
  {
    id: "rt-001b",
    name: "Game Boy Color — Crystal Clear Edition",
    slug: "game-boy-color-crystal-clear-edition",
    category: "Retro Gaming",
    shortDescription: "A fully transparent optical chassis showcasing bare recapped circuitry, laminated IPS backlit display, and USB-C power.",
    description: "The Crystal Clear edition celebrates pure electronic transparency. Every surface reveals the restored circuit board underneath, descaled tantalum capacitors, gold trace jumpers, and polished internal mechanics. Equipped with a custom FunnyPlaying 2.6\" high-brightness IPS panel, tactile silicone conductive pads, CleanAmp audio boost, and a rechargeable 1800mAh battery module.",
    price: 175000,
    originalReleaseYear: 1998,
    edition: "01 / 02",
    status: "limited",
    stock: 1,
    era: "90s",
    condition: "Pristine Upgraded",
    featured: true,
    dropId: "drop-001",
    dropName: "DROP 001 — THE REBIRTH COLLECTION",
    highlightTag: "LIMITED DROP",
    storyQuote: "Complete optical transparency. Nothing hidden, every trace and solder joint celebrated as mechanical architecture.",
    beforeImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1000&q=80",
    afterImage: "https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1531525645387-7f14be1bdbbd?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=85",
    ],
    specifications: [
      { label: "Base Hardware", value: "Nintendo Game Boy Color (CGB-001, 1998)" },
      { label: "Display Architecture", value: "Laminated 2.6\" IPS Panel with OSD menu & 5 retro scanline modes" },
      { label: "Audio Overhaul", value: "CleanAmp Pro v1.2 with ceramic transducer speaker & zero noise floor" },
      { label: "Power System", value: "1,800 mAh LiPo rechargeable battery with USB-C port" },
      { label: "Shell & Buttons", value: "Optical clear UV-stabilized polycarbonate shell with white tactile membranes" },
      { label: "Capacitor Type", value: "Solid tantalum SMD low-ESR capacitors" },
      { label: "Edition Authenticity", value: "Hand-etched serial plate RT-GBC-002 (Numbered 01 / 02)" },
    ],
    restorationStages: [
      {
        stage: "FOUND",
        title: "01 — Deep Storage Recovery",
        description: "Recovered from an estate collection with dead power traces and cloudy casing.",
        image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "DISASSEMBLED",
        title: "02 — Complete Disassembly",
        description: "Stripped to individual chassis brackets and bare PCB substrate.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "RESTORED",
        title: "03 — Ultrasonic Descaling",
        description: "Submerged in heated ultrasonic solvent neutralizer bath to restore pure copper conduction.",
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "UPGRADED",
        title: "04 — Optical Glass & USB-C",
        description: "Milled crystal chassis to seat laminated IPS screen and fast USB-C charge port.",
        image: "https://images.unsplash.com/photo-1531525645387-7f14be1bdbbd?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "TESTED",
        title: "05 — Burn-in QC Bench",
        description: "12-hour continuous test cycle monitoring battery thermals and button response.",
        image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "REBORN",
        title: "06 — Drop Archive Boxing",
        description: "Delivered in anti-static ESD packaging with certificates of restoration.",
        image: "https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?auto=format&fit=crop&w=800&q=80",
      },
    ],
  },
  {
    id: "rt-001c",
    name: "Game Boy Advance — Midnight Edition",
    slug: "game-boy-advance-midnight-edition",
    category: "Retro Gaming",
    shortDescription: "Obsidian matte black GBA with laminated 3.0\" IPS display, tactile microswitches, CleanJuice USB-C, and stealth amber accents.",
    description: "The ultimate expression of stealth industrial design for the Game Boy Advance. Finished in matte obsidian black with tactile microswitched D-pad and shoulder triggers, edge-to-edge laminated 3.0\" IPS display with 4x integer scaling, CleanAmp audio boost, and USB-C fast charging. Reconditioned motherboard with tantalum capacitors and gold-plated cartridge pins.",
    price: 210000,
    originalReleaseYear: 2001,
    edition: "01 / 02",
    status: "coming-soon",
    stock: 1,
    era: "00s",
    condition: "Pristine Upgraded",
    featured: true,
    dropId: "drop-001",
    dropName: "DROP 001 — THE REBIRTH COLLECTION",
    highlightTag: "COMING SOON",
    storyQuote: "Midnight black ergonomics. 720x480 pixel perfection. Built for deep night gaming sessions.",
    beforeImage: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=1000&q=80",
    afterImage: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=1200&q=85",
    ],
    specifications: [
      { label: "Base Hardware", value: "Nintendo Game Boy Advance (AGB-001, 2001)" },
      { label: "Display Architecture", value: "3.0\" Laminated IPS (720x480, 4x integer scaling, 15 brightness steps)" },
      { label: "Trigger Actuation", value: "Tactile mechanical microswitches (85g actuation force)" },
      { label: "Power System", value: "1,700 mAh CleanJuice USB-C rechargeable battery pack" },
      { label: "Audio Overhaul", value: "CleanAmp 2W speaker amplifier with low-pass ground plane noise floor filter" },
      { label: "Chassis Finish", value: "Matte obsidian black polymer with stealth dark amber accents" },
      { label: "Edition Authenticity", value: "Hand-etched serial plate RT-GBA-001 (Numbered 01 / 02)" },
    ],
    restorationStages: [
      {
        stage: "FOUND",
        title: "01 — Salvage Sourcing",
        description: "Recovered from a private collector warehouse with unlit scratched screen and worn switches.",
        image: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "DISASSEMBLED",
        title: "02 — Precision Teardown",
        description: "Completely separated down to bare motherboard, volume potentiometer, and cartridge pins.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "RESTORED",
        title: "03 — Sonic Descaling & Recapping",
        description: "PCB submerged in ultrasonic bath and recapped with solid tantalum SMD capacitors.",
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "UPGRADED",
        title: "04 — IPS Lamination & CleanJuice Mod",
        description: "Installed laminated glass IPS panel and CleanJuice USB-C fast charging kit.",
        image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "TESTED",
        title: "05 — Clock Stability & Thermal Bench",
        description: "Overclock and thermal dissipation test under multi-cartridge load.",
        image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "REBORN",
        title: "06 — Presentation Boxing",
        description: "Packaged with magnetic acrylic stand, braided USB-C cable, and numbered plaque.",
        image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80",
      },
    ],
  },
  {
    id: "rt-002",
    name: "iPod Classic — Midnight Edition",
    slug: "ipod-classic-midnight-edition",
    category: "Music",
    shortDescription: "Original 5.5th Gen 'Wolfson DAC' architecture rebuilt with 512GB silent solid-state storage, 3000mAh battery, and obsidian anodized chassis.",
    description: "Audiophiles revere the iPod Video 5.5th generation for its legendary Wolfson Microelectronics WM8758 DAC. We took this legendary sonic platform, extracted the failing mechanical Toshiba hard drive, and installed a custom quad-microSD solid-state converter with 512GB of silent high-speed flash storage. Wrapped in a bespoke PVD coated obsidian midnight mirror backplate and powered by a mammoth 3,000mAh battery capable of 90 continuous hours of FLAC playback.",
    price: 220000,
    originalReleaseYear: 2006,
    edition: "01 / 02",
    status: "low-stock",
    stock: 1,
    era: "00s",
    condition: "Masterpiece 1-of-1",
    featured: true,
    dropId: "drop-001",
    dropName: "DROP 001 — THE REBIRTH COLLECTION",
    highlightTag: "ONLY 1 REMAINING",
    storyQuote: "10,000 songs in your pocket was Apple's promise in 2001. Now, it holds your entire uncompressed lossless library with the warmest analog DAC ever built.",
    beforeImage: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1000&q=80",
    afterImage: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=85",
    ],
    specifications: [
      { label: "Hardware Model", value: "Apple iPod Video 5.5th Gen (Enhanced Search Firmware)" },
      { label: "Digital-to-Analog Converter", value: "Wolfson Microelectronics WM8758 (Pure analog tone)" },
      { label: "Storage Architecture", value: "512GB iFlash Quad Solid-State Storage (Zero moving parts)" },
      { label: "Battery Performance", value: "3,000 mAh High-Density Cell (Up to 90 hours audio playback)" },
      { label: "Chassis Finish", value: "Diamond-Like Carbon (DLC) Midnight Obsidian PVD Coating" },
      { label: "Click Wheel Response", value: "Recalibrated capacitive sensor with tactile ceramic feedback" },
      { label: "Firmware", value: "Dual-Boot: Stock Apple OS + Rockbox 3.15 (Lossless FLAC/ALAC)" },
    ],
    restorationStages: [
      {
        stage: "FOUND",
        title: "01 — Disk Error Recovery",
        description: "Retrieved with the infamous 'Sad iPod' hard drive click-of-death and a heavily tarnished rear stainless steel shell.",
        image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "DISASSEMBLED",
        title: "02 — Clean Separation",
        description: "Pried open with non-marring carbon spudgers to protect delicate ribbon cables and the click wheel bus.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "RESTORED",
        title: "03 — Wolfson Line Stage Conditioning",
        description: "Audio output capacitors swapped with audio-grade tantalum caps to deepen bass frequency response below 20Hz.",
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "UPGRADED",
        title: "04 — Flash Solid-State & 3000mAh Cell",
        description: "Replaced 30GB spinning magnetic platters with dual 256GB SanDisk Extreme cards on an ultra-slim controller board.",
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "TESTED",
        title: "05 — THD + Noise Calibration",
        description: "A/B audio benchmarked against high-end desktop reference DACs using Audio Precision spectrum analysis.",
        image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "REBORN",
        title: "06 — Final Polishing & Box Packaging",
        description: "Finished in custom black velvet presentation case with a 30-pin braided copper interconnect cable.",
        image: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80",
      },
    ],
  },
  {
    id: "rt-003",
    name: "Game Boy Advance — Glacier Edition",
    slug: "game-boy-advance-glacier-edition",
    category: "Retro Gaming",
    shortDescription: "Ergonomic masterpiece refitted with an edge-to-edge laminated 3.0\" IPS display, tactile microswitch buttons, and wireless audio.",
    description: "The horizontal layout of the original Game Boy Advance remains the pinnacle of handheld gaming ergonomics. We preserved the iconic Glacier frost silhouette while replacing the notoriously dark reflective panel with a 720x480 laminated IPS screen with integer 4x pixel scaling. We also integrated clicky tactile microswitches beneath the D-pad and shoulder triggers for crisp contemporary actuation, alongside Bluetooth 5.0 audio transmitter module.",
    price: 165000,
    originalReleaseYear: 2001,
    edition: "02 / 04",
    status: "available",
    stock: 2,
    era: "00s",
    condition: "Pristine Upgraded",
    featured: true,
    dropId: "drop-001",
    dropName: "DROP 001 — THE REBIRTH COLLECTION",
    highlightTag: "DROP 001",
    storyQuote: "No more angling your Game Boy toward bedroom lamps. Pure, razor-sharp pixel fidelity anywhere on Earth.",
    beforeImage: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=1000&q=80",
    afterImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1200&q=85",
    ],
    specifications: [
      { label: "Form Factor", value: "Nintendo Game Boy Advance (AGB-001, 2001)" },
      { label: "Display", value: "3.0\" Laminated IPS (720x480, 4x integer scaling, 15 brightness steps)" },
      { label: "Trigger Actuation", value: "Tactile mechanical microswitches (85g actuation force)" },
      { label: "Battery", value: "1,700 mAh CleanJuice USB-C rechargeable battery pack" },
      { label: "Sound", value: "CleanAmp 2W speaker amplifier with low-pass ground plane noise floor filter" },
      { label: "Connectivity", value: "Integrated Bluetooth 5.0 transmitter + 3.5mm analog jack" },
    ],
    restorationStages: [
      {
        stage: "FOUND",
        title: "01 — Yellowed Estate Discovery",
        description: "Rescued from an estate auction. Plastic shell had yellowed from UV light, and the power switch had built up resistive oxidation.",
        image: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "DISASSEMBLED",
        title: "02 — Teardown & Chemical Restoration",
        description: "Shell treated with stabilized peroxide retrobrite UV bath to reverse 25 years of bromine fire-retardant discoloration.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "RESTORED",
        title: "03 — Motherboard Ultrasonic Cleaning",
        description: "Volume wheel potentiometer and power rail switches completely desoldered, cleaned with deoxidizer, and reseated.",
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "UPGRADED",
        title: "04 — IPS Lamination & USB-C Mod",
        description: "Installed pre-laminated FunnyPlaying IPS panel and integrated custom USB-C charging battery pack.",
        image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "TESTED",
        title: "05 — 100-Hour Standby & Play QC",
        description: "Validated over multiple full charge cycles with diverse GBA cartridges to ensure rock-solid clock stability.",
        image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "REBORN",
        title: "06 — Numbered Collector Case",
        description: "Delivered in laser-engraved acrylic magnetic display stand and waterproof foam carry case.",
        image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
      },
    ],
  },
  {
    id: "rt-004",
    name: "Mechanical Keyboard — Rebuilt 01",
    slug: "mechanical-keyboard-rebuilt-01",
    category: "Keyboards",
    shortDescription: "Heavyweight 1989 industrial terminal chassis rebuilt with Lubed Gateron Oil Kings, QMK/VIA programmable hot-swap PCB, and solid brass internal weight.",
    description: "Born as a mainframe terminal keyboard from a shuttered German telecommunications hub, this industrial beast features a rigid 2.4kg enclosure made of structural polycarbonate. We discarded the dry membrane circuitry, custom laser-cut a 4mm blasted brass switch plate, installed a hot-swappable RP2040 programmable PCB running VIA firmware, hand-lubricated 87 Gateron Oil King linear switches with Krytox 205g0, and capped it with retro two-tone PBT dye-sublimated keycaps.",
    price: 295000,
    originalReleaseYear: 1989,
    edition: "01 / 01",
    status: "available",
    stock: 1,
    era: "80s",
    condition: "Masterpiece 1-of-1",
    featured: true,
    dropId: "drop-001",
    dropName: "DROP 001 — THE REBIRTH COLLECTION",
    highlightTag: "1 OF 1 BESPOKE",
    storyQuote: "Modern keyboards feel like plastic toys. Rebuilt 01 feels like typing on a granite vault with the acoustic resonance of a mechanical raindrop.",
    beforeImage: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1000&q=80",
    afterImage: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=85",
    ],
    specifications: [
      { label: "Original Base", value: "Siemens/Nixdorf Industrial Workstation Keyboard (1989)" },
      { label: "Total Net Weight", value: "2.85 kg (6.28 lbs) with internal solid brass damping block" },
      { label: "Switches", value: "Gateron Oil King Linears (55g actuation, hand-lubed with Krytox 205g0)" },
      { label: "Stabilizers", value: "Durock V2 Screw-in stabilizers (Holee-modded & lubed with XHT-BDZ)" },
      { label: "Firmware Support", value: "QMK / VIA instantaneous remapping with layer toggles" },
      { label: "Acoustic Dampening", value: "Custom laser-cut Poron foam gaskets + IXPE switch pads" },
      { label: "Port", value: "Detachable aviator GX16 connector to braided USB-C cable" },
    ],
    restorationStages: [
      {
        stage: "FOUND",
        title: "01 — Telecom Graveyard",
        description: "Found under a layer of industrial coal dust in an abandoned switching office, its DIN-5 cable severed.",
        image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "DISASSEMBLED",
        title: "02 — Structural Separation",
        description: "Heavy chassis dismantled. Original foam pad had turned to tar and was chemically dissolved with citrus solvents.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "RESTORED",
        title: "03 — Sandblasting & Case Refinishing",
        description: "Polycarbonate casing hand-buffed and coated with anti-static ceramic sealant to preserve matte tactile grain.",
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "UPGRADED",
        title: "04 — Custom Brass Plate & Hot-Swap PCB",
        description: "Milled 4mm solid brass plate and mated it with an ultra-low latency RP2040 hot-swappable PCB.",
        image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "TESTED",
        title: "05 — Sound Chamber Frequency Analysis",
        description: "Calibrated key-by-key for consistent acoustic frequency resonance between 180Hz and 220Hz (the ideal 'thock').",
        image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "REBORN",
        title: "06 — Collector Delivery Box",
        description: "Includes custom coiled aviator USB-C cable in carbon sleeve, solid titanium keycap puller, and test print sheet.",
        image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=800&q=80",
      },
    ],
  },
  {
    id: "rt-005",
    name: "Retro Camera — Chrome Revival",
    slug: "retro-camera-chrome-revival",
    category: "Cameras",
    shortDescription: "1974 full mechanical 35mm rangefinder fully CLA'd, fitted with real black shark-skin leatherette and laser-collimated 50mm f/1.4 optic.",
    description: "Before cameras were disposable microchips, they were high-precision clockwork Swiss watches made of brass gears and German glass. This 1974 rangefinder suffered from frozen shutter curtain timings and fungus between inner lens elements. We undertook a complete 32-hour CLA overhaul: dismantled the shutter governor, cleaned aperture blades in naphtha, replaced all decayed foam light seals with precision die-cut closed-cell silicone, and re-covered the body in genuine vulcanite shark-skin leatherette.",
    price: 340000,
    originalReleaseYear: 1974,
    edition: "01 / 02",
    status: "available",
    stock: 1,
    era: "Vintage",
    condition: "Collector Edition",
    featured: true,
    dropId: "drop-001",
    dropName: "DROP 001 — THE REBIRTH COLLECTION",
    highlightTag: "VINTAGE MASTERPIECE",
    storyQuote: "No batteries needed to capture a memory. A mechanical clockwork precision instrument ready for another 50 years of silver halide chemistry.",
    beforeImage: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1000&q=80",
    afterImage: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=1200&q=85",
    ],
    specifications: [
      { label: "Original Architecture", value: "Mechanical 35mm Coupled Rangefinder (1974)" },
      { label: "Shutter Mechanism", value: "Horizontal cloth focal-plane shutter (1/1000s to 1s + B)" },
      { label: "Optic System", value: "Multi-coated 50mm f/1.4 prime lens (De-fungused & laser collimated)" },
      { label: "Rangefinder Accuracy", value: "Calibrated dual-image split-prism with 98% contrast beam-splitter" },
      { label: "Exterior Trim", value: "High-polish mirror chrome brass top plate + Italian black leatherette" },
      { label: "Light Seal Upgrade", value: "Precision CNC cut closed-cell silicone light baffles (zero light leak guaranteed)" },
      { label: "Film Compatibility", value: "Standard 35mm film cassettes (Color & B&W)" },
    ],
    restorationStages: [
      {
        stage: "FOUND",
        title: "01 — Attic Basement Recovery",
        description: "Seized mechanism with sticky aperture blades and disintegrated gummy sponge seals inside the film back door.",
        image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "DISASSEMBLED",
        title: "02 — Teardown of 140 Clockwork Parts",
        description: "Every spring, escapement pawl, and optical element extracted onto labeled magnetic work trays.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "RESTORED",
        title: "03 — Full CLA Overhaul",
        description: "Ultrasonic bath in reagent-grade cleaning solutions, re-lubricated with Swiss Moebius synthetic horological oils.",
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "UPGRADED",
        title: "04 — Optical Recoating & Laser Collimation",
        description: "Rear element fungus eradicated under UV sterilization and infinity focus alignment calibrated on an optical collimator bench.",
        image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "TESTED",
        title: "05 — Electronic Shutter Speed Benchmark",
        description: "All shutter speeds tested across 1/1000s, 1/500s, and 1/250s with laser timing sensors to within +/- 3% accuracy.",
        image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "REBORN",
        title: "06 — Presentation Box with Test Negatives",
        description: "Ships with genuine leather neck strap, machined brass screw-in lens hood, and a developed roll of test negatives.",
        image: "https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=800&q=80",
      },
    ],
  },
  {
    id: "rt-006",
    name: "Tech Artifact — Motherboard No. 001",
    slug: "tech-artifact-motherboard-no-001",
    category: "Tech Art",
    shortDescription: "A decommissioned 1988 UNIX workstation motherboard suspended in optical acrylic, floating gold circuit traces, and hand-rubbed anodized aluminum shadow box.",
    description: "Silicon architecture is the modern world's cathedral sculpture. We took a decommissioned Sun Microsystems SPARCstation motherboard from 1988, desoldered fragile batteries that cause rot, chemically stabilized the fibreglass substrate, highlighted the 24-karat gold wire-bonded chip dies, and suspended the entire 12-layer board inside an optical-grade shadow frame with anti-reflective museum glass and subtle edge-lit amber luminescent glow.",
    price: 185000,
    originalReleaseYear: 1988,
    edition: "01 / 01",
    status: "available",
    stock: 1,
    era: "80s",
    condition: "Masterpiece 1-of-1",
    featured: true,
    dropId: "drop-001",
    dropName: "DROP 001 — THE REBIRTH COLLECTION",
    highlightTag: "SCULPTURE 1 OF 1",
    storyQuote: "Once driving the computational backbone of scientific discovery, now preserved forever as an eternal work of industrial art.",
    beforeImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80",
    afterImage: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1555680202-c86f0e12f086?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=1200&q=85",
    ],
    specifications: [
      { label: "Artifact Base", value: "Sun Microsystems RISC Workstation Mainboard (1988)" },
      { label: "Dimensions", value: "480mm x 380mm x 45mm (Wall mount or desk stance)" },
      { label: "Silicon Architecture", value: "Ceramic SPARC RISC Processor with pure gold bonding wires" },
      { label: "Preservation Grade", value: "Acid-free archival encapsulation with UV-99 museum glass" },
      { label: "Frame Construction", value: "Matte black anodized aircraft-grade aluminum frame" },
      { label: "Lighting", value: "Concealed 2200K warm amber micro-LED perimeter glow (USB powered)" },
      { label: "Authentication", value: "Deep laser engraved titanium authenticity plate RT-ART-001" },
    ],
    restorationStages: [
      {
        stage: "FOUND",
        title: "01 — Decommissioned Server Room",
        description: "Recovered from an obsolete government weather satellite tracking facility destined for scrap e-waste shredders.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "DISASSEMBLED",
        title: "02 — Hazardous Material Depletion",
        description: "Removed leaking NiCad CMOS barrel batteries and corroded electrolytic capacitors that would degrade over decades.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "RESTORED",
        title: "03 — Chemical Stabilization",
        description: "Substrate sealed with non-reflective archival grade clear polymer to prevent future copper and silver sulfide oxidation.",
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "UPGRADED",
        title: "04 — Optical Decap & Suspension",
        description: "Etched processor heat spreader to reveal the mesmerizing geometric silicon die beneath under ambient light.",
        image: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "TESTED",
        title: "05 — Hermetic Seal & Pressure Validation",
        description: "Enclosed in a nitrogen-purged hermetic enclosure to ensure absolute lifetime dust and moisture resistance.",
        image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "REBORN",
        title: "06 — Gallery Mounting & Plaque",
        description: "Mounted with French cleat wall mounting bracket and signed certificate by the lead preservation engineer.",
        image: "https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80",
      },
    ],
  },
  {
    id: "rt-007",
    name: "Braun Atelier — Audio Revival Unit",
    slug: "braun-atelier-audio-revival-unit",
    category: "Music",
    shortDescription: "Dieter Rams 1982 minimalist audio design re-engineered with wireless aptX Lossless Bluetooth, balanced pre-amplification, and motorized volume attenuation.",
    description: "Dieter Rams established the timeless rules of good design at Braun. This Atelier receiver unit from 1982 epitomizes 'less, but better'. We kept the exquisite cast metal chassis, tactile push-buttons, and weighted volume knob, while upgrading the internal amplifier circuitry to modern Class-D high-efficiency discrete components with 24-bit/96kHz Bluetooth audio receiver seamlessly hidden inside the original chassis.",
    price: 410000,
    originalReleaseYear: 1982,
    edition: "01 / 01",
    status: "sold-out",
    stock: 0,
    era: "80s",
    condition: "Masterpiece 1-of-1",
    featured: false,
    dropId: "drop-001",
    dropName: "DROP 001 — THE REBIRTH COLLECTION",
    highlightTag: "ARCHIVED DROP",
    storyQuote: "Good design is as little design as possible. We respected Rams' vision while bringing its acoustic heart into the 21st century streaming era.",
    beforeImage: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1000&q=80",
    afterImage: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=85",
    ],
    specifications: [
      { label: "Design Heritage", value: "Dieter Rams Braun Atelier Series (Germany, 1982)" },
      { label: "Amplification", value: "2x 75W RMS Class-D audiophile stage with Nichicon Fine Gold capacitors" },
      { label: "Wireless Protocol", value: "Qualcomm QCC5125 Bluetooth 5.2 (aptX HD, LDAC 990kbps support)" },
      { label: "Chassis Material", value: "Extruded anodized anthracite grey aluminum with matte bevels" },
      { label: "Phono Preamp", value: "Integrated high-fidelity RIAA MM/MC phono stage for turntables" },
      { label: "Status", value: "Sold Out to Private Collection, Lagos" },
    ],
    restorationStages: [
      {
        stage: "FOUND",
        title: "01 — Estate Discovery",
        description: "Recovered from an architect's private studio with blown transformer coils and scorched bridge rectifiers.",
        image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "DISASSEMBLED",
        title: "02 — Precision Teardown",
        description: "Modular chassis separated while preserving factory silkscreen markings on the faceplate.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "RESTORED",
        title: "03 — Toroidal Power Conversion",
        description: "Replaced obsolete humming AC transformer with custom shielded ultra-quiet toroidal power unit.",
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "UPGRADED",
        title: "04 — Lossless Wireless Integration",
        description: "Antenna concealed inside non-conductive rear port grommet for invisible Bluetooth streaming.",
        image: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "TESTED",
        title: "05 — Continuous 48hr Acoustic Load",
        description: "Benchmarked through Bowers & Wilkins monitor speakers across acoustic jazz and deep synthesized bass.",
        image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "REBORN",
        title: "06 — Permanent Archive Seal",
        description: "Delivered to collector with certificate of origin and custom walnut dust cover.",
        image: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80",
      },
    ],
  },
  {
    id: "rt-008",
    name: "Cyberdeck Terminal — Prototype 00",
    slug: "cyberdeck-terminal-prototype-00",
    category: "Custom Builds",
    shortDescription: "Custom handcrafted portable field deck built into a restored 1978 rugged aluminum field enclosure with ultrawide bar LCD and ortholinear mechanical switches.",
    description: "Inspired by the cyberpunk vision of William Gibson's Neuromancer, this one-of-a-kind field computing terminal was built from the restored shell of a 1978 British avionics calibration casing. Powered by an embedded Linux compute engine, featuring an ultra-crisp 8.8\" 1920x480 bar display, mechanical Kailh Choc low-profile switches, hot-swappable dual 18650 cells, and hardware GPIO breakout toggle switches with brass flip guards.",
    price: 380000,
    originalReleaseYear: 1978,
    edition: "01 / 01",
    status: "available",
    stock: 1,
    era: "Vintage",
    condition: "Masterpiece 1-of-1",
    featured: false,
    dropId: "drop-001",
    dropName: "DROP 001 — THE REBIRTH COLLECTION",
    highlightTag: "RESERVE COMMMISSION",
    storyQuote: "Physical toggles. Satisfying tactile mechanical switches. A true standalone offline computational instrument built for survival.",
    beforeImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80",
    afterImage: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=85",
    ],
    specifications: [
      { label: "Enclosure", value: "Milspec aluminum avionics instrument housing (London, 1978)" },
      { label: "Display Module", value: "8.8\" IPS Bar Display (1920x480 resolution, 60Hz, 600 nits)" },
      { label: "Processing Engine", value: "Quad-Core ARM Cortex-A72 with 8GB LPDDR4 & 256GB NVMe" },
      { label: "Keyboard Matrix", value: "40% Ortholinear PCB with Kailh Choc Low Profile Burnt Orange switches" },
      { label: "Physical Controls", value: "Heavy-duty brass toggle switches with illuminated status lamps" },
      { label: "Power System", value: "Hot-swap dual 18650 Panasonic Li-Ion cells with built-in battery gauge" },
    ],
    restorationStages: [
      {
        stage: "FOUND",
        title: "01 — Surplus Enclosure Recovery",
        description: "Discovered at an industrial electronics scrap yard with rusted steel rivets and flaking military enamel.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "DISASSEMBLED",
        title: "02 — Strip & Bead Blast",
        description: "Stripped down to virgin aluminum alloy and bead-blasted to achieve a uniform tactile gunmetal finish.",
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "RESTORED",
        title: "03 — Custom CNC Faceplate Milling",
        description: "Machined 3mm aerospace aluminum front faceplate to house the ultrawide display and custom ortholinear switch bed.",
        image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "UPGRADED",
        title: "04 — Linux OS & Terminal Integration",
        description: "Custom lightweight Arch Linux build with retro amber terminal theme and instant 2-second boot.",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "TESTED",
        title: "05 — Drop & Environmental QC",
        description: "Tested for ruggedness, switch debounce reliability, and thermal dissipation under continuous compile load.",
        image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
      },
      {
        stage: "REBORN",
        title: "06 — Commission Ready",
        description: "Supplied with pelican case, external high-gain stubby antenna, and 65W GaN fast charger.",
        image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
      },
    ],
  },
];
